kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pure-block
  dataSource:
    kind: VolumeSnapshot
    name: mysql-pv-snapshot
    apiGroup: snapshot.storage.k8s.io
