apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mysql-pv-snapshot
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: mysql-pv-claim
    kind: PersistentVolumeClaim
